branches:
  only: master
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
after_success:
  - cd build
  - find . -type f -exec curl --ftp-create-dirs -T {} --user ${FTP_USER}:${FTP_PASSWORD} ftp://${FTP_HOST}/{} \;
